import { ReactNode } from 'react';
import '../globals.css';

export const metadata = {
  title: 'Przemysław Szelenberger Portfolio',
  description: 'Generated by create next app + Sanity',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
