import '../globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Przemysław Szelenberger Portfolio',
  description: 'Generated by create next app + Sanity',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header>
          <Link
            className="
              bg-gradient-to-r
              from-orange-400
              via-rose-600
              to-purple-600
              bg-clip-text
              text-transparent
              text-lg
              font-bold
            "
            href="/"
          >
            Przemysław Szelenberger
          </Link>
        </header>
        <main className="py-20">
          {children}
        </main>
      </body>
    </html>
  );
}
